# Contents of /data/local/tmp/com.yourcompany.yourapp-geckoview-config.yaml

env:
  MOZ_LOG: nsHttp:5


prefs:
  network.proxy.type:  1
  network.proxy.socks:  "127.0.0.1"
  network.proxy.socks_port:  9050
  network.proxy.socks_version:  5
  network.proxy.socks_remote_dns:  true
  permissions.default.image:  2
  browser.display.show_image_placeholders: true
  browser.cache.disk.enable: false
  browser.cache.memory.enable: true
  browser.cache.disk.capacity: 0
  privacy.resistFingerprinting: true
  privacy.donottrackheader.enabled: false
  privacy.donottrackheader.value: 1
  network.http.sendRefererHeader:  0
  security.checkloaduri: false
  security.mixed_content.block_active_content: false
  security.mixed_content.block_display_content:  false
  media.peerconnection.enabled: false //webrtc disabled
  browser.cache.disk_cache_ssl: true
  signon.formlessCapture.enabled: true
  signon.storeWhenAutocompleteOff: true
  dom.event.contextmenu.enabled: true
  layout.css.visited_links_enabled: true
  security.ssl3.ecdhe_rsa_aes_128_sha: true
  security.ssl3.ecdhe_ecdsa_aes_128_sha: true
  security.ssl3.dhe_rsa_aes_128_sha: true
  security.ssl3.rsa_des_ede3_sha: true
  security.ssl3.dhe_rsa_aes_256_sha: true
  browser.safebrowsing.blockedURIs.enabled: false
  media.gmp-provider.enabled: false
  browser.send_pings.require_same_host: false
  webgl.disabled: false
  pdfjs.enableWebGL: false
  browser.safebrowsing.malware.enabled: false
  security.csp.experimentalEnabled: false
  network.http.referer.spoofSource: false
  security.OCSP.require: false
  security.ssl.require_safe_negotiation: false
  privacy.clearOnShutdown.cache: true
  privacy.clearOnShutdown.downloads: true
  privacy.clearOnShutdown.formdata: true
  privacy.clearOnShutdown.history: true
  privacy.clearOnShutdown.offlineApps: true
  privacy.clearOnShutdown.passwords: true
  privacy.clearOnShutdown.sessions: true
  privacy.clearOnShutdown.siteSettings: true



